### ISSUE TITLE
关于论文代码的一些问题

### ISSUE THREAD

**Issue by Airgods** [heekhero/ACSR#1]
您好，不好意思打扰您了，请问下这里代码中meta_test_ACSR文件是将模型的训练和测试都放在了一起吗还是只有测试部分，，我在其中的微调部分看到了参数的更新，我的理解是模型在评估时参数是不更新的，但是全部代码看起来又像是仅仅在做测试，所以不太懂

**Comment by heekhero** [comment]
您好，meta_test_ACSR仅涉及到Meta-test时候的逻辑，但其中包含在每一个小任务上finetune的过程。
